blank_issues_enabled: true
contact_links:
  - name: ğŸ“– Documentation
    url: https://statikfintechllc.github.io/The_GateKeepers_Riddle.Interactive/
    about: Check out the interactive riddle game
